### ISSUE TITLE
broken under ruby 2.1.5

### ISSUE THREAD

**Issue by bejbus** [angdraug/samizdat#8]
Samizdat: 2015-01-24 16:53:39 +0300: ArgumentError: not delegated
Error ID: 4ff36ee041b8166a4c1c7844a2188623
Site: test
Route: /
CGI parameters: {}
Backtrace:
/usr/lib/ruby/2.1.0/delegate.rb:392:in `__getobj__'
/usr/lib/ruby/2.1.0/delegate.rb:341:in `block in delegating_block'
/usr/lib/ruby/vendor_ruby/samizdat/models/member.rb:117:in `initialize'
/usr/lib/ruby/vendor_ruby/samizdat/models/member.rb:20:in `new'
/usr/lib/ruby/vendor_ruby/samizdat/models/member.rb:20:in `initialize'

**Comment by angdraug** [comment]
Fix was merged in 876c58ab273cc9298a2fcf2a9bc8a53e62c9e456.
